name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and Setup Project
      run: yarn install

      test:
        needs: install
        steps:
        - name: Lint / Tests
          run: |
            yarn lint
            yarn test
    env:
      CI: true
