name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  install_project:
      name: Install and Configure Project
      runs-on: ubuntu-latest
      env:
        CI: true
      steps:
        - uses: actions/checkout@v1
        - name: Install and Setup Project
          run: yarn install

  lint_tests:
    runs-on: ubuntu-latest
    name: Run Linter and Unit Tests
    needs: install_project
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Lint / Tests
        run: |
          yarn lint
          yarn test
