name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Project
      run: yarn install
    - name: Run lint and Tests
      run: |
        yarn lint
        yarn test
